## 양방향(Bidirectional) RNN

In [1]:
import tensorflow as tf

sentence = "What time is it ?"
dic = {
    "is": 0,
    "it": 1,
    "What": 2,
    "time": 3,
    "?": 4
}

sentence_tensor = tf.constant([[dic[word] for word in sentence.split()]])

embedding_layer = tf.keras.layers.Embedding(input_dim=len(dic), output_dim=100)
emb_out = embedding_layer(sentence_tensor)

print("입력 문장 데이터 형태:", emb_out.shape)

bi_rnn = \
tf.keras.layers.Bidirectional(
    tf.keras.layers.SimpleRNN(units=64, use_bias=False, return_sequences=True)
)
bi_out = bi_rnn(emb_out)

print("Bidirectional RNN 결과 (최종 Step Output):", bi_out.shape)

Metal device set to: Apple M1 Pro
입력 문장 데이터 형태: (1, 5, 100)
Bidirectional RNN 결과 (최종 Step Output): (1, 5, 128)


In [2]:
print(bi_out)

tf.Tensor(
[[[ 9.66837443e-03 -6.14537159e-03  3.34645584e-02  1.89178239e-03
   -3.51388007e-02 -2.05916017e-02 -8.42656754e-03 -1.50548294e-02
    7.32100941e-03 -4.30459064e-03  1.05638364e-02 -4.87648100e-02
   -2.21819226e-02  1.52616343e-02  4.04134888e-04 -1.57921333e-02
    1.07519869e-02  9.24507622e-03  1.79591682e-02 -2.51479410e-02
   -4.47051711e-02  3.71209569e-02 -2.40748171e-02 -5.83017953e-02
   -2.80890148e-02  1.34733217e-02  2.53909193e-02  6.15232736e-02
    4.88326363e-02 -1.71753839e-02 -9.99565050e-03  1.44100357e-02
    4.97097336e-02  3.19184102e-02 -2.44148225e-02 -2.03312244e-02
    3.50296348e-02  3.35938093e-04  9.93854925e-03  2.44424138e-02
   -5.35982102e-02  3.71933430e-02  2.36007180e-02  7.38837384e-03
   -1.15205301e-03 -7.85224885e-03 -6.88739195e-02  6.90936968e-02
   -1.40088508e-02  4.89335172e-02 -3.52844708e-02 -4.60013188e-03
   -2.82201339e-02  1.78406257e-02  4.48158477e-03  3.52959707e-02
    1.28037883e-02  2.85849092e-03 -1.99648384e-02 

In [5]:
simple_rnn = tf.keras.layers.SimpleRNN(units=64, use_bias=False, return_sequences=True)

simple_out = bi_rnn(emb_out)

print("Simple RNN 결과 (최종 Step Output):", simple_out.shape)

Simple RNN 결과 (최종 Step Output): (1, 5, 128)


In [6]:
simple_out

<tf.Tensor: shape=(1, 5, 128), dtype=float32, numpy=
array([[[ 9.66837443e-03, -6.14537159e-03,  3.34645584e-02,
          1.89178239e-03, -3.51388007e-02, -2.05916017e-02,
         -8.42656754e-03, -1.50548294e-02,  7.32100941e-03,
         -4.30459064e-03,  1.05638364e-02, -4.87648100e-02,
         -2.21819226e-02,  1.52616343e-02,  4.04134888e-04,
         -1.57921333e-02,  1.07519869e-02,  9.24507622e-03,
          1.79591682e-02, -2.51479410e-02, -4.47051711e-02,
          3.71209569e-02, -2.40748171e-02, -5.83017953e-02,
         -2.80890148e-02,  1.34733217e-02,  2.53909193e-02,
          6.15232736e-02,  4.88326363e-02, -1.71753839e-02,
         -9.99565050e-03,  1.44100357e-02,  4.97097336e-02,
          3.19184102e-02, -2.44148225e-02, -2.03312244e-02,
          3.50296348e-02,  3.35938093e-04,  9.93854925e-03,
          2.44424138e-02, -5.35982102e-02,  3.71933430e-02,
          2.36007180e-02,  7.38837384e-03, -1.15205301e-03,
         -7.85224885e-03, -6.88739195e-02,  6.9