In [2]:
import tensorflow as tf

vocab = {      # 사용할 단어 사전 정의
    "i": 0,
    "need": 1,
    "some": 2,
    "more": 3,
    "coffee": 4,
    "cake": 5,
    "cat": 6,
    "dog": 7
}

sentence = "i i i i need some more coffee coffee coffee"
# 위 sentence
_input = [vocab[w] for w in sentence.split()]  # [0, 0, 0, 0, 1, 2, 3, 4, 4, 4]

vocab_size = len(vocab)   # 8

one_hot = tf.one_hot(_input, vocab_size)
print(one_hot.numpy())    # 원-핫 인코딩 벡터를 출력해 봅시다.

Metal device set to: Apple M1 Pro
[[1. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]]


In [3]:
distribution_size = 2   # 보기 좋게 2차원으로 분산 표현하도록 하죠!
linear = tf.keras.layers.Dense(units=distribution_size, use_bias=False)
one_hot_linear = linear(one_hot)

print("Linear Weight")
print(linear.weights[0].numpy())

print("\nOne-Hot Linear Result")
print(one_hot_linear.numpy())

Linear Weight
[[ 0.28436923  0.3404385 ]
 [ 0.13790494  0.11280537]
 [-0.19440633  0.6290488 ]
 [ 0.02977383 -0.60317576]
 [-0.35331386 -0.6685755 ]
 [ 0.00211787 -0.33654046]
 [ 0.16598731  0.26231825]
 [ 0.48362947  0.5397022 ]]

One-Hot Linear Result
[[ 0.28436923  0.3404385 ]
 [ 0.28436923  0.3404385 ]
 [ 0.28436923  0.3404385 ]
 [ 0.28436923  0.3404385 ]
 [ 0.13790494  0.11280537]
 [-0.19440633  0.6290488 ]
 [ 0.02977383 -0.60317576]
 [-0.35331386 -0.6685755 ]
 [-0.35331386 -0.6685755 ]
 [-0.35331386 -0.6685755 ]]
